spring:
  application:
    name: sosh-price-management-ms

  data:
    mongodb:
      database: soshealth
      uri: mongodb://soshealth:oUoGMmS5r4gPGltAoiT10bJsCnEsNrTQZZNM4veYjjtVSAsrbmlDXuZTewRdCKreWZdIZ79iglWttqR6gUArMw==@soshealth.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@soshealth@

server:
  servlet:
    context-path: /sosPriceManagement/v1
  http2:
    enabled: true
  port: 446
